# Generated by Django 3.2.16 on 2023-08-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
