# Generated by Django 3.2.16 on 2023-08-31 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
